# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\ncalculator\"-\n\x11\x43\x61lculatorRequest\x12\x0b\n\x03op1\x18\x01 \x01(\x05\x12\x0b\n\x03op2\x18\x02 \x01(\x05\"#\n\x0f\x43\x61lculatorReply\x12\x10\n\x08response\x18\x01 \x01(\x05\x32\xa1\x02\n\nCalculator\x12\x44\n\x04Mult\x12\x1d.calculator.CalculatorRequest\x1a\x1b.calculator.CalculatorReply\"\x00\x12\x43\n\x03\x44iv\x12\x1d.calculator.CalculatorRequest\x1a\x1b.calculator.CalculatorReply\"\x00\x12\x43\n\x03Sub\x12\x1d.calculator.CalculatorRequest\x1a\x1b.calculator.CalculatorReply\"\x00\x12\x43\n\x03\x41\x64\x64\x12\x1d.calculator.CalculatorRequest\x1a\x1b.calculator.CalculatorReply\"\x00\x62\x06proto3')



_CALCULATORREQUEST = DESCRIPTOR.message_types_by_name['CalculatorRequest']
_CALCULATORREPLY = DESCRIPTOR.message_types_by_name['CalculatorReply']
CalculatorRequest = _reflection.GeneratedProtocolMessageType('CalculatorRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATORREQUEST,
  '__module__' : 'calc_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculatorRequest)
  })
_sym_db.RegisterMessage(CalculatorRequest)

CalculatorReply = _reflection.GeneratedProtocolMessageType('CalculatorReply', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATORREPLY,
  '__module__' : 'calc_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculatorReply)
  })
_sym_db.RegisterMessage(CalculatorReply)

_CALCULATOR = DESCRIPTOR.services_by_name['Calculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCULATORREQUEST._serialized_start=26
  _CALCULATORREQUEST._serialized_end=71
  _CALCULATORREPLY._serialized_start=73
  _CALCULATORREPLY._serialized_end=108
  _CALCULATOR._serialized_start=111
  _CALCULATOR._serialized_end=400
# @@protoc_insertion_point(module_scope)
